blogs/urls.py
from django.urls import path

from blogs.views import BlogsListViews, BlogsDetailViews

app_name = 'blogs'

urlpatterns = [
    path('', BlogsListViews.as_view(), name='list'),
    path('detail/<int:pk>/', BlogsDetailViews.as_view(), name='detail'),
]

limupa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from pages.views import HomePageView, ContactTemplatesView, AboutTemplatesView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplatesView.as_view(), name='contact'),
    path('about/', AboutTemplatesView.as_view(), name='about'),
]

products/urls.py
from django.urls import path

from products.views import ProductsListViews

app_name = 'products'

urlpatterns = [
    path('', ProductsListViews.as_view(), name='list'),
]

blogs/models.py
from django.db import models


class AuthorModel(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='blog-authors')
    about = models.TextField()
    position = models.CharField(max_length=128)
    profession = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogModel(models.Model):
    title = models.CharField(max_length=128)
    image = models.ImageField(upload_to='blog-images')
    short_info = models.TextField(null=True)
    content = models.TextField()
    category = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    author = models.ForeignKey(AuthorModel, related_name='blogs', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

pages/models.py
from django.db import models


class ContactModel(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

products/models.py
from django.db import models


class ProductCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product Category'
        verbose_name_plural = 'Product Categories'


class ProductTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product Tag'
        verbose_name_plural = 'Product Tags'


class ProductColorModel(models.Model):
    name = models.CharField(max_length=128)
    code = models.CharField(max_length=6)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product Color'
        verbose_name_plural = 'Product Colors'


class ProductSizeModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product Size'
        verbose_name_plural = 'Product Sizes'


class ProductManufactureModel(models.Model):
    name = models.CharField(max_length=128)
    logo = models.ImageField(null=True, blank=True, upload_to='manufacture/')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product Manufacture'
        verbose_name_plural = 'Product Manufactures'


class ProductModel(models.Model):
    image1 = models.ImageField(upload_to='products/')

    name = models.CharField(max_length=225)
    long_description = models.TextField()
    short_description = models.CharField(max_length=225)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.PositiveIntegerField(default=0)
    sku = models.CharField(max_length=10, unique=True)
    count = models.PositiveIntegerField()

    manufacture = models.ForeignKey(ProductManufactureModel, on_delete=models.CASCADE, related_name='products')
    colors = models.ManyToManyField(ProductColorModel, related_name='products')
    tags = models.ManyToManyField(ProductTagModel, related_name='products')
    categories = models.ManyToManyField(ProductCategoryModel, related_name='products')
    sizes = models.ManyToManyField(ProductSizeModel, related_name='products')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

blogs/views.py
from django.views.generic import ListView, DetailView

from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel


class BlogsListViews(ListView):
    template_name = 'blog-list.html'
    context_object_name = 'blogs'
    model = BlogModel
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        blogs = BlogModel.objects.all().order_by('-created_at')
        cat = self.request.GET.get('cat')

        if cat:
            blogs = blogs.filter(category__in=cat)

        tags = BlogTagModel.objects.all()
        tag = self.request.GET.get('tag')

        if tag:
            tags = tags.filter(tags__in=tag)

        context = {
            'blogs': blogs,
            'categories': BlogCategoryModel.objects.all(),
            'tags': BlogTagModel.objects.all(),
            'famous_blogs': BlogModel.objects.all().order_by('-created_at'),
        }
        return context


class BlogsDetailViews(DetailView):
    template_name = 'blog-details.html'
    context_object_name = 'blog'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):


        context = {
            'categories': BlogCategoryModel.objects.all(),
            'blog': BlogModel.objects.get(pk=self.kwargs['pk']),
            'tags': BlogTagModel.objects.all(),
            'famous_blogs': BlogModel.objects.all().order_by('-created_at'),
        }
        return context

pages/views.py
from django.views.generic import TemplateView, CreateView

from pages.form import ContactModelForm


class HomePageView(TemplateView):
    template_name = 'home.html'


class ContactTemplatesView(CreateView):
    template_name = 'contact.html'
    form_class = ContactModelForm
    success_url = '/'


class AboutTemplatesView(TemplateView):
    template_name = 'about-us.html'

products/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import ProductModel


class ProductsListViews(ListView):
    template_name = 'product-list.html'
    model = ProductModel
    context_object_name = 'products'

templates/blog-filter.html
{% load static %}
<div class="col-lg-3 order-lg-1 order-2">
    <div class="li-blog-sidebar-wrapper">
        <div class="li-blog-sidebar">
            <div class="li-sidebar-search-form pt-xs-30 pt-sm-30">
                <form action="#">
                    <input type="text" class="li-search-field" placeholder="search here">
                    <button type="submit" class="li-search-btn"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
        <div class="li-blog-sidebar pt-25">
            <h4 class="li-blog-sidebar-title">Categories</h4>
            {% for cat in categories %}
            <ul class="li-blog-archive">
                <li><a href="?cat={{ cat.id }}">{{ cat.name }}</a></li>
            </ul>
            {% endfor %}
        </div>
        <div class="li-blog-sidebar">
            <h4 class="li-blog-sidebar-title">Recent Post</h4>
            {% for blog in famous_blogs %}
            <div class="li-recent-post pb-30">
                <div class="li-recent-post-thumb">
                    <a href="{% url 'blogs:detail' pk=blog.id %}">
                        <img class="img-full" src="{{ blog.image.url }}" alt="Li's Product Image">
                    </a>
                </div>
                <div class="li-recent-post-des">
                    <span><a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title }}</a></span>
                    <span class="li-post-date">{{ blog.created_at }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="li-blog-sidebar">
            <h4 class="li-blog-sidebar-title">Tags</h4>
            <ul class="li-blog-tags">
                {% for tag in tags %}
                <li><a href="?tag={{ tag.id }}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog-list.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
    
<!-- blog-list-left-sidebar31:55-->
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Blog List Left Sidebar || limupa - Digital Products Store eCommerce Bootstrap 4 Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}">
        <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/venobox.css' %}">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/helper.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
        <script>
            function addUrlParameter(name, value) {
                let searchParams = new URLSearchParams(window.location.search)
                if (searchParams.has(name) && searchParams.get(name) === value){
                    searchParams.delete(name)
                }else{
                    searchParams.set(name, value)
                }
                window.location.search = searchParams.toString()
            }
        </script>
    </head>
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">Home</a></li>
                            <li class="active">Blog List Left Sidebar</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Li's Main Blog Page Area -->
            <div class="li-main-blog-page pt-60 pb-55">
                <div class="container">
                    <div class="row">
                        <!-- Begin Li's Blog Sidebar Area -->
                        {% include 'blog-filter.html' %}
                        <!-- Li's Blog Sidebar Area End Here -->
                        <!-- Begin Li's Main Content Area -->
                        <div class="col-lg-9 order-lg-2 order-1">
                            <div class="row li-main-content">
                                {% for blog in blogs %}
                                <div class="col-lg-12">
                                    <div class="li-blog-single-item mb-30">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="li-blog-banner">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}"><img class="img-full" src="{{ blog.image.url }}" alt=""></a>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="li-blog-content">
                                                    <div class="li-blog-details">
                                                        <h3 class="li-blog-heading pt-xs-25 pt-sm-25"><a href="blog-details.html">{{ blog.title }}</a></h3>
                                                        <div class="li-blog-meta">
                                                            <a class="author" href="{% url 'blogs:detail' pk=blog.id %}"><i class="fa fa-user"></i>{{ blog.author.name }}</a>
                                                            <a class="comment" href="{% url 'blogs:detail' pk=blog.id %}"><i class="fa fa-comment-o"></i> 3 comment</a>
                                                            <a class="post-time" href="{% url 'blogs:detail' pk=blog.id %}"><i class="fa fa-calendar"></i>{{ blog.created_at }}</a>
                                                        </div>
                                                        <p>{{ blog.short_info }}</p>
                                                        <a class="read-more" href="{% url 'blogs:detail' pk=blog.id %}">Read More...</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                <!-- Begin Li's Pagination Area -->
                                <div class="col-lg-12">
                                    <div class="li-paginatoin-area text-center pt-25">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <ul class="li-pagination-box">
                                                {% if page_obj.has_previous %}
                                                    <li>
                                                        <a class="Previous" href="?page={{ page_obj.previous_page_number }}">
                                                            Previous
                                                        </a>
                                                    </li>
                                                {% endif %}
                                                    {% for page in page_obj.paginator.page_range %}
                                                    <li  class="active">
                                                        <a href="#">
                                                            {{ page }}
                                                        </a>
                                                    </li>
                                                    {% endfor %}
                                                {% if page_obj.has_next %}
                                                    <li>
                                                        <a class="Next" href="?page={{ page_obj.next_page_number }}">
                                                            Next
                                                        </a>
                                                    </li>
                                                {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Li's Pagination End Here Area -->
                            </div>
                        </div>
                        <!-- Li's Main Content Area End Here -->
                    </div>
                </div>
            </div>
            <!-- Li's Main Blog Page Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/ajax-mail.js' %}"></script>
        <script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
        <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
        <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/waypoints.min.js' %}"></script>
        <script src="{% static 'js/jquery.barrating.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/venobox.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/scrollUp.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/login-register.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
    
<!-- login-register31:27-->
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Login Register || limupa - Digital Products Store eCommerce Bootstrap 4 Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
        <!-- Material Design Iconic Font-V2.2.0 -->
        <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <!-- Font Awesome Stars-->
        <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}">
        <!-- Meanmenu CSS -->
        <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
        <!-- owl carousel CSS -->
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <!-- Slick Carousel CSS -->
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <!-- Animate CSS -->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <!-- Jquery-ui CSS -->
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
        <!-- Venobox CSS -->
        <link rel="stylesheet" href="{% static 'css/venobox.css' %}">
        <!-- Nice Select CSS -->
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <!-- Bootstrap V4.1.3 Fremwork CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Helper CSS -->
        <link rel="stylesheet" href="{% static 'css/helper.css' %}">
        <!-- Main Style CSS -->
        <link rel="stylesheet" href="../assets/{% static 'css/style.css' %}">
        <!-- Responsive CSS -->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <!-- Modernizr js -->
        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    </head>
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">Home</a></li>
                            <li class="active">Login Register</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Login Content Area -->
            <div class="page-section mb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6 mb-30">
                            <!-- Login Form s-->
                            <form action="#" >
                                <div class="login-form">
                                    <h4 class="login-title">Login</h4>
                                    <div class="row">
                                        <div class="col-md-12 col-12 mb-20">
                                            <label>Email Address*</label>
                                            <input class="mb-0" type="email" placeholder="Email Address">
                                        </div>
                                        <div class="col-12 mb-20">
                                            <label>Password</label>
                                            <input class="mb-0" type="password" placeholder="Password">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="check-box d-inline-block ml-0 ml-md-2 mt-10">
                                                <input type="checkbox" id="remember_me">
                                                <label for="remember_me">Remember me</label>
                                            </div>
                                        </div>
                                        <div class="col-md-4 mt-10 mb-20 text-left text-md-right">
                                            <a href="#"> Forgotten pasward?</a>
                                        </div>
                                        <div class="col-md-12">
                                            <button class="register-button mt-0">Login</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                            <form action="#">
                                <div class="login-form">
                                    <h4 class="login-title">Register</h4>
                                    <div class="row">
                                        <div class="col-md-6 col-12 mb-20">
                                            <label>First Name</label>
                                            <input class="mb-0" type="text" placeholder="First Name">
                                        </div>
                                        <div class="col-md-6 col-12 mb-20">
                                            <label>Last Name</label>
                                            <input class="mb-0" type="text" placeholder="Last Name">
                                        </div>
                                        <div class="col-md-12 mb-20">
                                            <label>Email Address*</label>
                                            <input class="mb-0" type="email" placeholder="Email Address">
                                        </div>
                                        <div class="col-md-6 mb-20">
                                            <label>Password</label>
                                            <input class="mb-0" type="password" placeholder="Password">
                                        </div>
                                        <div class="col-md-6 mb-20">
                                            <label>Confirm Password</label>
                                            <input class="mb-0" type="password" placeholder="Confirm Password">
                                        </div>
                                        <div class="col-12">
                                            <button class="register-button mt-0">Register</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Login Content Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
        <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
        <!-- Popper js -->
        <script src="{% static 'js/vendor/popper.min.js' %}"></script>
        <!-- Bootstrap V4.1.3 Fremwork js -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Ajax Mail js -->
        <script src="{% static 'js/ajax-mail.js' %}"></script>
        <!-- Meanmenu js -->
        <script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
        <!-- Wow.min js -->
        <script src="{% static 'js/wow.min.js' %}"></script>
        <!-- Slick Carousel js -->
        <script src="{% static 'js/slick.min.js' %}"></script>
        <!-- Owl Carousel-2 js -->
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <!-- Magnific popup js -->
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <!-- Isotope js -->
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <!-- Imagesloaded js -->
        <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <!-- Mixitup js -->
        <script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
        <!-- Countdown -->
        <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
        <!-- Counterup -->
        <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
        <!-- Waypoints -->
        <script src="{% static 'js/waypoints.min.js' %}"></script>
        <!-- Barrating -->
        <script src="{% static 'js/jquery.barrating.min.js' %}"></script>
        <!-- Jquery-ui -->
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <!-- Venobox -->
        <script src="{% static 'js/venobox.min.js' %}"></script>
        <!-- Nice Select js -->
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <!-- ScrollUp js -->
        <script src="{% static 'js/scrollUp.min.js' %}"></script>
        <!-- Main/Activator js -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>

<!-- login-register31:27-->
</html>